trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  username: $(username)
  password: $(password)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'finaldevopstestsc'
    backendAWSBucketName: 'devopstfstate'
    backendAWSKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'finaldevopstestsc'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'finaldevopstestsc'
    variableSet: |        
        username=$(username)
        password=$(password) 
