trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'finaldevopstestsc'
    backendAWSBucketName: 'devopstfstate'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'finaldevopstestsc'
    backendServiceAWS: 'finaldevopstestsc'
    backendAWSBucketName: 'devopstfstate'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'finaldevopstestsc'
    backendServiceAWS: 'finaldevopstestsc'
    backendAWSBucketName: 'devopstfstate'
    backendAWSKey: 'terraform.tfstate'