trigger:
- main

pool:
  name: vartikatestpool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'newdevopstestproj-githubtestproject'
    backendAWSBucketName: 'devopstfstate'
    backendAWSKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'newdevopstestproj-githubtestproject'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'newdevopstestproj-githubtestproject'
